-- THE ULTIMATE MYSQL BOOTCAMP: GO FROM SQL BEGINNER TO EXPERT

-- FETCH DATA FROM TABLES
SELECT * FROM <TABLE_NAME>

SELECT * FROM CUSTOMERS; 

SELECT * FROM ORDERS; 

SELECT * FROM PRODUCTS ORDER BY PRICE DESC;
.
SELECT CUSTOMERNAME, COUNT(*) AS 'NUMBER OF ORDERS' FROM CUSTOMERS
INNER JOIN ORDERS ON ORDERS.CUSTOMERID = CUSTOMERS.CUSTOMERID
GROUP BY CUSTOMERS.CUSTOMERID;

SELECT CUSTOMERNAME, COUNT(*) AS 'NUMBER OF ORDERS' FROM CUSTOMERS
INNER JOIN ORDERS ON ORDERS.CUSTOMERID = CUSTOMERS.CUSTOMERID
GROUP BY CUSTOMERNAME;


-- ****************** WORKING WITH DATABASES ****************** --

-- LIST ALL DATABSES
SHOW DATABASES; 

-- CREATE NEW DATABASES
CREATE DATABASE <NAME>;
CREATE DATABASE HELLO_WORLD;

-- DELETE DATABASE
DROP DATABASE <NAME>;

-- USING DATABASES
USE <DATABASE NAME>;

-- CURRENTLY SELECTED DATABASE
SELECT DATABASE();

-- ****************** WORKING WITH TABLES ****************** --

-- LIST ALL TABLES
SHOW TABLES;

-- LIST ALL TABLE COLUMNS
SHOW COLUMNS FROM <TABLE_NAME>;
DESC <NAME>;

-- CREATE NEW TABLE
CREATE TABLE <NAME> (<COLUMN_NAME> <DATA_TYPE>,..);

CREATE TABLE CAT (
  NAME VARCHAR(100),
  AGE INT
);

-- DELETE TABLE
DROP TABLE <TABLE_NAME>; 
DROP TABLE CATS; 

-- DELETE ALL RECORDS FROM TABLE
TRUNCATE TABLE <TABLE_NAME>;

-- INSERT DATA INTO TABLE
INSERT INTO <TABLE NAME> (COLUMN1, COLUMN2)
VALUES ('COLUMN1VALUE', 'COLUMN2VALUE');

INSERT INTO CATS (NAME, AGE)
VALUES ('BOB', 7);

-- MULTIPLE INSERT
INSERT INTO TABLE_NAME (COLUMN_NAME, COLUMN_NAME) 
VALUES  (VALUE, VALUE), 
        (VALUE, VALUE), 
        (VALUE, VALUE);

-- CHECK WARNINGS RELATED TO LAST QUERY
SHOW WARNINGS;

-- ****************** WORKING WITH TABLE CONTSTAINTS ****************** --

-- CREATE COLUMNS WITH DEFAULT VALUES

CREATE TABLE cats3 (
  name VARCHAR(20) DEFAULT 'no name provided',
  age INT DEFAULT 99
);

-- NOTICE THE CHANGE WHEN YOU DESCRIBE THE TABLE:
DESC cats3; 

-- INSERT A CAT WITHOUT A NAME:
INSERT INTO cats3(age) VALUES(13); 

-- OR A NAMELESS, AGELESS CAT:
INSERT INTO cats3() VALUES(); 

-- COMBINE NOT NULL AND DEFAULT:
CREATE TABLE cats4 (
    name VARCHAR(20) NOT NULL DEFAULT 'unnamed',
    age INT NOT NULL DEFAULT 99
  );
  
-- NOTICE THE DIFFERENCE:
INSERT INTO cats4() VALUES();
INSERT INTO cats4(name, age) VALUES('Montana', NULL);

-- CODE: A PRIMER ON PRIMARY KEYS
-- DEFINE A TABLE WITH A PRIMARY KEY CONSTRAINT:

CREATE TABLE unique_cats (
  cat_id INT NOT NULL,
  name VARCHAR(100),
  age INT,
  PRIMARY KEY (cat_id)
);

DESC unique_cats; 

-- INSERT SOME NEW CATS:
INSERT INTO unique_cats(cat_id, name, age) VALUES(1, 'Fred', 23);
 
INSERT INTO unique_cats(cat_id, name, age) VALUES(2, 'Louise', 3);
 
INSERT INTO unique_cats(cat_id, name, age) VALUES(1, 'James', 3);
-- NOTICE WHAT HAPPENS:

SELECT * FROM unique_cats; 

-- Adding in AUTO_INCREMENT:

CREATE TABLE unique_cats2 (
    cat_id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100),
    age INT,
    PRIMARY KEY (cat_id)
);

-- INSERT A COUPLE NEW CATS:
INSERT INTO unique_cats2(name, age) VALUES('Skippy', 4);
INSERT INTO unique_cats2(name, age) VALUES('Jiff', 3);
INSERT INTO unique_cats2(name, age) VALUES('Jiff', 3);
INSERT INTO unique_cats2(name, age) VALUES('Jiff', 3);
INSERT INTO unique_cats2(name, age) VALUES('Skippy', 4);

-- Notice the difference:
SELECT * FROM unique_cats2; 


-- TABLE CONSTRAINTS EXERCISE SOLUTION
CREATE TABLE employees (
    id INT AUTO_INCREMENT NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    age INT NOT NULL,
    current_status VARCHAR(255) NOT NULL DEFAULT 'employed',
    PRIMARY KEY(id)
);

-- ANOTHER WAY OF DEFINING A PRIMARY KEY:
CREATE TABLE employees (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    age INT NOT NULL,
    current_status VARCHAR(255) NOT NULL DEFAULT 'employed'
);

-- A TEST INSERT:
INSERT INTO employees(first_name, last_name, age) VALUES ('Dora', 'Smith', 58);
